# Generated by Django 3.1.3 on 2020-11-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
